services:
  room-classifier-api:
    build:
      context: ..
      dockerfile: serving/Dockerfile
    container_name: room-classifier-api
    ports:
      - "8000:8000"
    volumes:
      - ../artifacts:/app/artifacts
      - ../models:/app/models
      - ../configs:/app/configs
    environment:
      - CONFIG_PATH=/app/configs/release/rc1_single.yaml
    restart: unless-stopped
